---
- name: Renew TLS certificate
  hosts: webserver
  become: yes

  tasks:
    - name: Include renewal tasks
      ansible.builtin.include_role:
        name: ../roles/certbot
        tasks_from: renew
