all:
  hosts:
    webserver:
      ansible_host: <IP-адрес вашего сервера>
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      domain_name: tls-lesson.ru
      email: your-email@example.com
